/**
 * @file pythonWorkspaceLib.ts
 * @description Bundled Python helper modules for the in-browser Pyodide sandbox environment.
 * Injected automatically into Pyodide's virtual filesystem at execution time.
 */

export const WORKSPACE_PYTHON_FILES: Record<string, string> = {
  "workspace.py": [
    '"""',
    'workspace.py wrapper re-exporting the workspace package.',
    '"""',
    'from workspace import llm, fs, agent, tools, LLMClient, Filesystem, AgentHelper, ToolHelper',
    '',
    '__all__ = ["llm", "fs", "agent", "tools", "LLMClient", "Filesystem", "AgentHelper", "ToolHelper"]',
    ''
  ].join("\n"),

  "agent_workspace.py": [
    'from workspace import llm, fs, agent, tools, LLMClient, Filesystem, AgentHelper, ToolHelper',
    ''
  ].join("\n"),

  "workspace/__init__.py": [
    '"""',
    'Workspace Python API Package.',
    'Provides zero-dependency Python utilities for LLM generation, filesystem access, agent memory, and tool execution.',
    '"""',
    'from .llm import LLMClient, llm',
    'from .fs import Filesystem, fs',
    'from .agent import AgentHelper, agent',
    'from .tools import ToolHelper, tools',
    '',
    '__all__ = ["LLMClient", "llm", "Filesystem", "fs", "AgentHelper", "agent", "ToolHelper", "tools"]',
    ''
  ].join("\n"),

  "workspace/llm.py": [
    '"""',
    'LLM generation module for workspace Python environment.',
    'Connects directly to workspace LLM completions endpoint using environment credentials.',
    '"""',
    'import os',
    'import json',
    '',
    '',
    '',
    'class LLMClient:',
    '    def __init__(self):',
    '        self.base_url = os.environ.get("OPENAI_BASE_URL", "").rstrip("/")',
    '        self.api_key = os.environ.get("OPENAI_API_KEY", "")',
    '        self.default_model = os.environ.get("LLM_MODEL", "")',
    '',
    '    def generate(self, prompt: str, system: str = None, model: str = None, temperature: float = 0.7) -> str:',
    '        messages = []',
    '        if system:',
    '            messages.append({"role": "system", "content": system})',
    '        messages.append({"role": "user", "content": prompt})',
    '        return self.chat(messages, model=model, temperature=temperature)',
    '',
    '    def chat(self, messages: list, model: str = None, temperature: float = 0.7) -> str:',
    '        if not self.base_url:',
    '            raise Exception("LLM Error: OPENAI_BASE_URL is not configured in Settings.")',
    '        ',
    '        target_model = model or self.default_model',
    '        if not target_model:',
    '            raise Exception("LLM Error: No LLM model configured. Please select or specify a model in Settings.")',
    '',
    '        base = self.base_url.rstrip("/")',
    '        if base.endswith("/chat/completions"):',
    '            url = base',
    '        elif base.endswith("/v1"):',
    '            url = f"{base}/chat/completions"',
    '        else:',
    '            url = f"{base}/v1/chat/completions"',
    '',
    '        if not url.startswith("http://") and not url.startswith("https://"):',
    '            url = f"http://{url}"',
    '',
    '        payload = {',
    '            "model": target_model,',
    '            "messages": messages,',
    '            "temperature": temperature',
    '        }',
    '        import js',
    '        xhr = js.XMLHttpRequest.new()',
    '        xhr.open("POST", url, False)',
    '        xhr.setRequestHeader("Content-Type", "application/json")',
    '        if self.api_key:',
    '            xhr.setRequestHeader("Authorization", f"Bearer {self.api_key}")',
    '        try:',
    '            xhr.send(json.dumps(payload))',
    '        except Exception as e:',
    '            raise Exception(f"LLM Connection Error: {str(e)}")',
    '        if xhr.status >= 200 and xhr.status < 300:',
    '            res_data = json.loads(xhr.responseText)',
    '            choices = res_data.get("choices", [])',
    '            if choices and len(choices) > 0:',
    '                return choices[0].get("message", {}).get("content", "")',
    '            return ""',
    '        else:',
    '            raise Exception(f"LLM API Error ({xhr.status}): {xhr.responseText}")',
    '',
    '    def structured(self, prompt: str, schema: dict = None, system: str = None, model: str = None) -> dict:',
    '        sys_prompt = system or "Output ONLY valid JSON matching the requested structure without markdown codeblocks or surrounding text."',
    '        full_prompt = prompt',
    '        if schema:',
    '            full_prompt += f"\\n\\nRequired JSON Schema:\\n{json.dumps(schema, indent=2)}"',
    '        raw_text = self.generate(full_prompt, system=sys_prompt, model=model, temperature=0.1)',
    '        clean = raw_text.strip()',
    '        if clean.startswith("```json"):',
    '            clean = clean[7:]',
    '        if clean.startswith("```"):',
    '            clean = clean[3:]',
    '        if clean.endswith("```"):',
    '            clean = clean[:-3]',
    '        return json.loads(clean.strip())',
    '',
    'llm = LLMClient()',
    ''
  ].join("\n"),

  "workspace/fs.py": [
    '"""',
    'Filesystem access module with agent permission enforcement.',
    '"""',
    'import os',
    'import json',
    'import shutil',
    '',
    'class Filesystem:',
    '    def __init__(self):',
    '        perms_raw = os.environ.get("AGENT_PERMISSIONS", "")',
    '        self.permissions = json.loads(perms_raw) if perms_raw else None',
    '        self.agent_id = os.environ.get("AGENT_ID", "")',
    '',
    '    def _normalize_path(self, path_str: str) -> str:',
    '        clean = str(path_str).replace("\\\\", "/").strip()',
    '        if clean.startswith("./"):',
    '            clean = clean[2:]',
    '        return clean.lstrip("/")',
    '',
    '    def _check_permission(self, path_str: str, mode: str = "read"):',
    '        if not self.permissions:',
    '            return',
    '        clean_path = self._normalize_path(path_str).lower()',
    '        allow_agent_folder = self.permissions.get("allowAgentFolderAccess", False)',
    '        if clean_path.startswith(".agents") and not allow_agent_folder:',
    '            if self.agent_id:',
    '                allowed_prefix = f".agents/{self.agent_id.lower()}"',
    '                if not (clean_path == allowed_prefix or clean_path.startswith(allowed_prefix + "/")):',
    '                    raise PermissionError(f"Access denied: Path \'{path_str}\' is inside protected .agents directory.")',
    '            else:',
    '                raise PermissionError(f"Access denied: Path \'{path_str}\' is inside protected .agents directory.")',
    '        allowed_list = self.permissions.get("allowedReadPaths" if mode == "read" else "allowedWritePaths")',
    '        if not allowed_list:',
    '            allowed_list = self.permissions.get("allowedPaths", ["/"])',
    '        if not allowed_list or "/" in allowed_list or "" in allowed_list:',
    '            return',
    '        is_ok = False',
    '        for prefix in allowed_list:',
    '            clean_prefix = self._normalize_path(prefix).lower()',
    '            if not clean_prefix or clean_prefix == "/" or clean_prefix == ".":',
    '                is_ok = True',
    '                break',
    '            if clean_path == clean_prefix or clean_path.startswith(clean_prefix + "/"):',
    '                is_ok = True',
    '                break',
    '        if not is_ok:',
    '            raise PermissionError(f"Permission Error ({mode}): Path \'{path_str}\' is restricted for agent \'{self.agent_id}\'.")',
    '',
    '    def read(self, path: str, encoding: str = "utf-8") -> str:',
    '        self._check_permission(path, "read")',
    '        with open(path, "r", encoding=encoding) as f:',
    '            return f.read()',
    '',
    '    def write(self, path: str, content: str, encoding: str = "utf-8"):',
    '        self._check_permission(path, "write")',
    '        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)',
    '        with open(path, "w", encoding=encoding) as f:',
    '            f.write(content)',
    '',
    '    def append(self, path: str, content: str, encoding: str = "utf-8"):',
    '        self._check_permission(path, "write")',
    '        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)',
    '        with open(path, "a", encoding=encoding) as f:',
    '            f.write(content)',
    '',
    '    def list(self, path: str = ".") -> list:',
    '        self._check_permission(path, "read")',
    '        return os.listdir(path)',
    '',
    '    def exists(self, path: str) -> bool:',
    '        return os.path.exists(path)',
    '',
    '    def is_file(self, path: str) -> bool:',
    '        return os.path.isfile(path)',
    '',
    '    def is_dir(self, path: str) -> bool:',
    '        return os.path.isdir(path)',
    '',
    '    def delete(self, path: str):',
    '        self._check_permission(path, "write")',
    '        if os.path.isdir(path):',
    '            shutil.rmtree(path)',
    '        elif os.path.exists(path):',
    '            os.remove(path)',
    '',
    'fs = Filesystem()',
    ''
  ].join("\n"),

  "workspace/agent.py": [
    '"""',
    'Agent context and memory persistence module.',
    '"""',
    'import os',
    'from .fs import fs',
    '',
    'class AgentHelper:',
    '    def __init__(self, fs_client):',
    '        self.agent_id = os.environ.get("AGENT_ID", "")',
    '        self.fs = fs_client',
    '',
    '    def get_id(self) -> str:',
    '        return self.agent_id',
    '',
    '    def save_memory(self, memory_text: str):',
    '        if not self.agent_id:',
    '            raise Exception("No active agent ID set in environment.")',
    '        mem_path = f".agents/{self.agent_id}/memories.txt"',
    '        self.fs.append(mem_path, f"- {memory_text.strip()}\\n")',
    '',
    '    def read_memories(self) -> str:',
    '        if not self.agent_id:',
    '            return ""',
    '        mem_path = f".agents/{self.agent_id}/memories.txt"',
    '        return self.fs.read(mem_path) if self.fs.exists(mem_path) else ""',
    '',
    'agent = AgentHelper(fs)',
    ''
  ].join("\n"),

  "workspace/tools.py": [
    '"""',
    'Tool execution helper module.',
    'Invokes authorized tools on behalf of the agent (e.g. read_file, write_file, search_wikipedia, etc.)',
    '"""',
    'import os',
    'import json',
    '',
    'import urllib.parse',
    'from .fs import fs',
    'from .agent import agent',
    '',
    'class ToolHelper:',
    '    def __init__(self, fs_client, agent_client):',
    '        self.fs = fs_client',
    '        self.agent = agent_client',
    '        perms_raw = os.environ.get("AGENT_PERMISSIONS", "")',
    '        self.permissions = json.loads(perms_raw) if perms_raw else None',
    '        self.agent_id = os.environ.get("AGENT_ID", "")',
    '',
    '    def _check_tool_permission(self, tool_name: str):',
    '        if not self.permissions:',
    '            return',
    '        allowed_tools = self.permissions.get("allowedTools", [])',
    '        if allowed_tools and tool_name not in allowed_tools:',
    '            raise PermissionError(f"Tool \'{tool_name}\' is not authorized for agent \'{self.agent_id}\'. Authorized tools: {allowed_tools}")',
    '',
    '    def execute_tool(self, tool_name: str, params: dict = None) -> dict:',
    '        if params is None:',
    '            params = {}',
    '        self._check_tool_permission(tool_name)',
    '        t = tool_name.lower()',
    '        if t == "search_wikipedia":',
    '            return {"result": self._search_wikipedia(params.get("query", ""), params.get("limit", 3))}',
    '        elif t == "read_file":',
    '            p = params.get("filePath") or params.get("path") or "."',
    '            return {"content": self.fs.read(p)}',
    '        elif t == "write_file":',
    '            p = params.get("filePath") or params.get("path")',
    '            c = params.get("content", "")',
    '            self.fs.write(p, c)',
    '            return {"status": "success", "path": p}',
    '        elif t == "list_dir":',
    '            p = params.get("path") or params.get("dirPath") or "."',
    '            return {"files": self.fs.list(p)}',
    '        elif t == "delete_file":',
    '            p = params.get("filePath") or params.get("path")',
    '            self.fs.delete(p)',
    '            return {"status": "deleted", "path": p}',
    '        elif t == "get_info":',
    '            p = params.get("filePath") or params.get("path") or "."',
    '            self.fs._check_permission(p, "read")',
    '            st = os.stat(p)',
    '            return {"path": p, "size": st.st_size, "is_file": os.path.isfile(p), "is_dir": os.path.isdir(p)}',
    '        elif t == "save_memory":',
    '            m = params.get("text") or params.get("memory") or ""',
    '            self.agent.save_memory(m)',
    '            return {"status": "memory_saved"}',
    '        else:',
    '            raise ValueError(f"Tool \'{tool_name}\' is not supported")',
    '',
    '    def _search_wikipedia(self, query: str, limit: int = 3) -> list:',
    '        import js',
    '        encoded_query = urllib.parse.quote(query)',
    '        url = f"https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch={encoded_query}&utf8=&format=json&origin=*"',
    '        xhr = js.XMLHttpRequest.new()',
    '        xhr.open("GET", url, False)',
    '        try:',
    '            xhr.send()',
    '            if xhr.status >= 200 and xhr.status < 300:',
    '                data = json.loads(xhr.responseText)',
    '                results = data.get("query", {}).get("search", [])[:limit]',
    '                clean_results = []',
    '                for r in results:',
    '                    snippet = r.get("snippet", "").replace(\'<span class="searchmatch">\', "").replace("</span>", "")',
    '                    clean_results.append({"title": r.get("title"), "snippet": snippet, "pageid": r.get("pageid")})',
    '                return clean_results',
    '            else:',
    '                return [{"error": f"Wikipedia search failed: HTTP {xhr.status}"}]',
    '        except Exception as e:',
    '            return [{"error": f"Wikipedia search failed: {str(e)}"}]',
    '',
    'tools = ToolHelper(fs, agent)',
    ''
  ].join("\n"),
};
